### ISSUE TITLE
include lib or script to decode lightninginvoice

### ISSUE THREAD

**Issue by iemwill** [bumi/fourohtwo#6]
There should be something on github...

**Comment by bumi** [comment]
what do you mean by this? 
We should probably do a user story somewhat like:
In order to review the payment as a user I want to see the invoice details before confirming and sending the payment. The details include the amount, memo, recipient. 

This means that we need to be able to decode the lightning invoice. This can be done using an RPC call to lnd: [decodepayreq](https://api.lightning.community/#decodepayreq)

**Comment by iemwill** [comment]
yes, how we get the info can be done with a rpc request to the lightning node. But exactly like a confirmation by the user, or an automatic confirmation that the amount we get from payment invoice is the same which the website needs, was the aim behind this issue.
